name: Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Update file timestamps based on last Git commit
        run: |
          git ls-files -z | while IFS= read -r -d '' file; do
            commit_date=$(git log -1 --format="%ci" "$file")
            adjusted_date=$(date -d "$commit_date 8 hours" "+%Y-%m-%d %H:%M:%S %z")
            # only for debug
            # echo "Updating timestamp for $file to $adjusted_date"
            touch -d "$adjusted_date" "$file"
          done
      - name: Use Node.js 21.7.1
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "21.7.1"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
